### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by blurHY** [blurHY/IPZN#1]
ZeroNet's competitor, IPFS, wins on low layer protocols.
 - Data deduplication
 - Works in China, because of DHT
 - Immutable, indicates the ability to archive, fie versioning

We will choose js-ipfs to implement first, so:
- Works in browser, completely
- Easy to popularize

What we need to do, is adding a compatibility layer:
- A server to serve APIs

Easy and revolutionary

**Comment by styromaniac** [comment]
Use browser APIs to store local copy of software and site files. This is possible.

**Comment by blurHY** [comment]
https://github.com/HelloZeroNet/ZeroNet/issues/1669

There's also a discussion here
